pi_pro/app1/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import index,detail,detail_update,master_img_index,master_csv,img_imp,chumon_imp,make_shijisho,download_shijisho, \
                    make_ship,download_ship,make_body,download_body,download_master,free


app_name="app1"
urlpatterns = [
    path('', index, name="index"),
    path('login/', auth_views.LoginView.as_view(template_name='app1/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('detail/<int:pk>/', detail, name="detail"),
    path('detail_update/', detail_update, name="detail_update"),
    path('master_img_index/', master_img_index, name="master_img_index"),
    path('master_csv/', master_csv, name="master_csv"),
    path('img_imp/', img_imp, name="img_imp"),
    path('chumon_imp/', chumon_imp, name="chumon_imp"),
    path('make_body/', make_body, name="make_body"),
    path('make_shijisho/', make_shijisho, name="make_shijisho"),
    path('make_ship/', make_ship, name="make_ship"),
    path('download_body/', download_body, name="download_body"),
    path('download_shijisho/', download_shijisho, name="download_shijisho"),
    path('download_ship/', download_ship, name="download_ship"),
    path('download_master/', download_master, name="download_master"),
    path('free/', free, name="free"),
]

pi_pro/pi_pro/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings # 追加
from django.conf.urls.static import static # 追加

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("app1.urls")),
]

# MEDIA_ROOTを公開する(アクセス可能にする)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pi_pro/app1/forms.py
from django.forms import ModelForm
from django import forms
from .models import Image

class Image_form(ModelForm):
    title=forms.CharField(
        label="タイトル",
        widget=forms.TextInput(attrs={"class":"form-control"}),
        required=True
    )
    image=forms.ImageField(
        label="イメージ図",
        widget=forms.FileInput(attrs={"class":"form-control"}),
        required=True
    )

    class Meta:
        model = Image
        fields = ['title','image']

pi_pro/app1/views.py
from django.shortcuts import render,redirect
import csv
from .models import Image,Master_all,Master_gsp,Master_shopify,Order_list,Order_detail,Factory
from .forms import Image_form
import io
from django.http import JsonResponse
import json
from django.db.models import Max,Min,Sum
import datetime
from django.http import HttpResponse
import urllib.parse
from django.contrib.auth.decorators import login_required


@login_required
def index(request):
    if "kubun" not in request.session:
        request.session["kubun"]=""
    if "order_num" not in request.session:
        request.session["order_num"]=""
    if "gara" not in request.session:
        request.session["gara"]=""
    if "maker_name" not in request.session:
        request.session["maker_name"]=""
    if "csv_list" not in request.session:
        request.session["csv_list"]=[]

    master_all=Master_all.objects.all()
    odr_list=Order_list.objects.all()
    order_list=[]
    odr_end=0
    for i in odr_list:
        ins=Order_detail.objects.filter(kubun=i.kubun,order_num=i.order_num)
        if ins.filter(body_check=0).count()==0 and ins.filter(shiji_check=0).count()==0 and ins.filter(ship_check=0).count()==0:
            odr_end=1
        li_hinmei=[]
        for h in ins:
            if h.hinmei not in li_hinmei:
                li_hinmei.append(h.hinmei)
        li_gara=[]
        li_print_way=[]
        li_shi_factory=[]
        li_maker_name=[]
        li_suryo=[]
        li_check=[]

        for h in li_hinmei:
            ins2=ins.filter(hinmei=h)
            li_gara.append(ins2[0].gara)

            print_point=eval(ins2[0].print_point)
            print_way=eval(ins2[0].print_way)
            pri_list=[]
            for j in range(len(print_point)):
                pri_list.append(print_point[j] + "：" + print_way[j])
            li_print_way.append(" 、 ".join(pri_list))

            li_shi_factory.append(ins2[0].shi_factory)
            li_maker_name.append(ins2[0].maker_name)
            li_suryo.append(ins2.aggregate(Sum("suryo"))["suryo__sum"])
            li_check.append([ins2[0].body_check,ins2[0].shiji_check,ins2[0].ship_check])

        dic={"order_id":i.id,"kubun":i.kubun, "order_day":i.order_day, "hinmei":li_hinmei, "gara":li_gara, "print_way":li_print_way,
             "factory":li_shi_factory, "maker":li_maker_name, "suryo":li_suryo, "check":li_check, "odr_end":odr_end}
        order_list.append(dic)
        
    params={
        "master_all":master_all,
        "order_list":order_list,
    }
    return render(request,"app1/index.html",params)


# 注文詳細
@login_required
def detail(request,pk):
    chumon=Order_list.objects.get(pk=pk)
    factory=Factory.objects.all()
    gara_list=list(Order_detail.objects.filter(kubun=chumon.kubun,order_num=chumon.order_num).values_list("gara",flat=True).order_by("gara").distinct())
    if chumon.kubun=="GSP":
        sender=Master_gsp.objects.filter(gara=gara_list[0])[0]

    item_list=[]
    for i in gara_list:
        detail=Order_detail.objects.filter(kubun=chumon.kubun,order_num=chumon.order_num,gara=i)
        dic={}
        dic["gara"]=i
        dic["img"]=Image.objects.get(title=detail[0].print_img).image.url
        dic["tantou"]=detail[0].shi_tantou or ""
        dic["seisaku"]=detail[0].shi_seisaku or ""
        dic["factory"]=detail[0].shi_factory
        dic["factory_day"]=detail[0].shi_factory_day or ""
        dic["body_day"]=detail[0].body_day or ""
        dic["bikou"]=detail[0].shi_bikou
        li=[]
        for i in detail:
            k=0
            js_1=json.loads(i.print_point)
            for h in range(len(js_1)):
                js_2=json.loads(i.print_way)
                js_3=json.loads(i.print_size_width)
                js_4=json.loads(i.print_size_height)
                js_5=json.loads(i.print_color)

                li_s=[k,i.maker_hinban,i.maker_hinmei,i.color,i.size,i.suryo,js_1[h],js_2[h],js_3[h],js_4[h],js_5[h],i.fukuro]
                li.append(li_s)
                k+=1
            
        dic["dtl"]=li
        dic["row_all"]=detail.count() * len(js_1)
        dic["row_point"]=len(js_1)

        if detail[0].shi_gara_first == "" or detail[0].shi_gara_first == None:
            gara_min=Order_detail.objects.filter(gara=i).aggregate(Min("gara_day"))["gara_day__min"]
            if  gara_min is None:
                dic["gara_first"]=datetime.date.today().strftime("%Y-%m-%d")
            else:
                dic["gara_first"]=gara_min
        else:
            dic["gara_first"]=detail[0].shi_gara_first

        if detail[0].shi_gara_last == "" or detail[0].shi_gara_last == None:
            gara_max=Order_detail.objects.filter(gara=i).aggregate(Max("gara_day"))["gara_day__max"]
            if  gara_max is None:
                dic["gara_last"]=""
            else:
                dic["gara_last"]=gara_max
        else:
            dic["gara_last"]=detail[0].shi_gara_last

        dic["moto_hinban"]=detail[0].shouhin_code
        dic["moto_hinmei"]=detail[0].hinmei

        item_list.append(dic)

    params={
        "chumon":chumon,
        "pk":pk,
        "item_list":item_list,
        "sender":sender,
        "factory":factory,
    }
    return render(request,"app1/detail.html",params)


# 注文内容変更
def detail_update(request):
    pk=request.POST.get("pk")
    od_li=Order_list.objects.get(id=pk)
    od_li.ship_com=request.POST.get("ship_com")
    od_li.ship_name=request.POST.get("ship_name")
    od_li.ship_yubin=request.POST.get("ship_yubin")
    od_li.ship_pref=request.POST.get("ship_pref")
    od_li.ship_city=request.POST.get("ship_city")
    od_li.ship_adress1=request.POST.get("ship_adress1")
    od_li.ship_adress2=request.POST.get("ship_adress2")
    od_li.ship_tel=request.POST.get("ship_tel")
    od_li.ship_limit=request.POST.get("ship_limit")
    od_li.ship_day=request.POST.get("ship_day")
    od_li.ship_time=request.POST.get("ship_time")
    od_li.save()
    d={}
    return JsonResponse(d)


# ボディ発注CSV作成
def make_body(request):
    chumon_kubun=request.POST.get("chumon_kubun")
    chumon_order_num=request.POST.get("chumon_order_num")
    gara=request.POST.get("gara")
    factory=request.POST.get("factory")
    body_day=request.POST.get("body_day")

    body_csv=[]
    a=["品番","商品名","カラー","カラーコード","サイズ","サイズコード","数量","見積番号","SKU","納入先","入荷予定日","発送伝票備考","加工発注番号-バージョン","商品発注番号"]
    body_csv.append(a)

    ins_det=Order_detail.objects.filter(kubun=chumon_kubun,order_num=chumon_order_num,gara=gara)
    for i in ins_det:
        a=[
            i.maker_hinban, #品番
            i.maker_hinmei, #商品名
            i.color, #カラー
            i.maker_color_code, #カラーコード
            i.size, #サイズ
            i.maker_size_code, #サイズコード
            i.suryo, #数量
            i.kubun + "_" + i.order_num, #見積番号
            i.maker_sku, #SKU
            factory, #納入先
            body_day, #入荷予定日
            "", #発送伝票備考
            i.kubun + "_" + i.order_num, #加工発注番号-バージョン
            "" #商品発注番号
        ]
        body_csv.append(a)

        # 発行済み
        i.body_check=1
        i.save()

    request.session["gara"]=gara
    request.session["kubun"]=chumon_kubun
    request.session["order_num"]=chumon_order_num
    request.session["maker_name"]=ins_det[0].maker_name
    request.session["csv_list"]=body_csv
    d={}
    return JsonResponse(d)


# ボディ発注CSVダウンロード
def download_body(request):
    kubun=request.session["kubun"]
    order_num=request.session["order_num"]
    gara=request.session["gara"]
    maker_name=request.session["maker_name"]
    ship_csv=request.session["csv_list"]
    now=datetime.datetime.now()
    filename=urllib.parse.quote(maker_name + "_" + kubun + "_" + str(order_num) +  "_" + gara +"_" + format(now,"%Y%m%d%H%M%S") +".csv")
    response = HttpResponse(content_type='text/csv; charset=CP932')
    response['Content-Disposition'] =  "attachment;  filename='{}'; filename*=UTF-8''{}".format(filename, filename)
    writer = csv.writer(response)
    for line in ship_csv:
        writer.writerow(line)
    return response


# 指示書CSV作成
def make_shijisho(request):
    chumon_kubun=request.POST.get("chumon_kubun")
    chumon_order_num=request.POST.get("chumon_order_num")
    gara=request.POST.get("gara")
    gara_first=request.POST.get("gara_first")
    gara_last=request.POST.get("gara_last")
    tantou=request.POST.get("tantou")
    seisaku=request.POST.get("seisaku")
    factory=request.POST.get("factory")
    factory_day=request.POST.get("factory_day")
    body_day=request.POST.get("body_day")
    bikou=request.POST.get("bikou")

    shiji_csv=[]
    a=["注文番号","氏名","配送先会社","配送先氏名","配送先郵便番号","配送先都道府県","配送先市町村","配送先番地","配送先ビル名","配送先電話番号",
       "送り主郵便番号","送り主都道府県","送り主市区町村","送り主番地建物","送り主会社名","送り主名前","送り主電話番号","納品期限","納品指定日","時間指定",
       "品番","品名","カラー","サイズ","数量","柄名","初回日","前回日","加工位置","加工方法","画像","画像URL","プリントサイズ_左右","プリントサイズ_天地",
       "プリント色（２次元配列）","袋詰め","加工場","加工場発送日","営業担当","制作担当","ボディ入荷日","備考"]
    shiji_csv.append(a)

    ins_li=Order_list.objects.get(kubun=chumon_kubun,order_num=chumon_order_num)
    ins_det=Order_detail.objects.filter(kubun=chumon_kubun,order_num=chumon_order_num,gara=gara)
    if chumon_kubun =="GSP":
        ins_mas=Master_gsp.objects.filter(gara=gara)[0]

    for i in ins_det:

        # Order_detail
        i.shi_gara_first=gara_first
        i.shi_gara_last=gara_last
        i.shi_factory=factory
        i.shi_factory_day=factory_day
        i.shi_tantou=tantou
        i.shi_seisaku=seisaku
        i.body_day=body_day
        i.shi_bikou=bikou
        i.gara_day=datetime.date.today().strftime("%Y-%m-%d")
        if i.img_url == None or i.img_url=="":
            i.img_url="https://pipro.pythonanywhere.com" + Image.objects.get(title=i.print_img).image.url
        i.shiji_check=1
        i.save()

        # CSV作成
        a=[
            chumon_kubun + "_" + str(chumon_order_num), #注文番号
            ins_li.order_name, #氏名
            ins_li.ship_com, #配送先会社
            ins_li.ship_name, #配送先氏名

pi_pro/app1/templates/app1/index.html
{% load humanize %}
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <title>Pi_pro　注文一覧</title>
</head>
<body>
    <div class="mt-3 mb-5" style="margin: 0 auto; width: 1300px;">

        <!-- メニュー -->
        <div>
            <a href="{% url 'app1:master_img_index' %}"><button class="btn btn-outline-primary" type="submit" name="btn_upload">マスタ取込</button></a>
        </div>

        <!--注文取込-->
        <div style="margin-top: 50px;">
            <form id="csv_form">{% csrf_token %}
                <div class="flex2">
                    <div>注文区分：</div>
                    <div>
                        <select class="form-control form-select" name="master_name">
                            {% for i in master_all %}
                            <option value="{{i.name}}">{{i.name}}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div style="margin-left: 20px;"><input class="form-control" type="file" name="csv1" id="csv1" style="width: 400px;"></div>
                    <div style="margin-left: 20px;"><button class="btn btn-primary" type="button" id="btn_upload" >注文取込</button></div>
                </div>  
            </form>
        </div>

        <!-- 注文一覧 -->
         <div style="margin-top: 100px;">
            <table class="table table-bordered">
                <tr>
                    <th>注文ID</th>
                    <th>注文日時</th>
                    <th>区分</th>
                    <th>商品名</th>
                    <th>柄名</th>
                    <th>数量</th>
                    <th>メーカー</th>
                    <th>加工場</th>
                    <th>加工方法</th>
                    <th>発行</th>
                </tr>
                {% for i in order_list %}
                    {% if i.odr_end == 1 %}
                    <tr style="background-color: #c0c0c0;">
                    {% else %}
                    <tr>
                    {% endif %}
                        <td style="text-align: center;"><a href="/detail/{{i.order_id}}">{{i.order_id}}</a></td>
                        <td>{{i.order_day}}</td>
                        <td>{{i.kubun}}</td>
                        <td>{% for h in i.hinmei %}{{h}}<br>{% endfor %}</td>
                        <td>{% for h in i.gara %}{{h}}<br>{% endfor %}</td>
                        <td style="text-align: center;">{% for h in i.suryo %}{{h}}<br>{% endfor %}</td>
                        <td>{% for h in i.maker %}{{h}}<br>{% endfor %}</td>
                        <td>{% for h in i.factory %}{% if h %}{{h}}{% endif %}<br>{% endfor %}</td>
                        <td>{% for h in i.print_way %}{{h}}<br>{% endfor %}</td>
                        <td>
                            {% for h in i.check %}
                                {% if h.0 == 1 %}<button class="btn btn-primary btn-sm" type="button">ボ</button>{% else %}　{% endif %}
                                {% if h.1 == 1 %}<button class="btn btn-success btn-sm" type="button">指</button>{% else %}　{% endif %}
                                {% if h.2 == 1 %}<button class="btn btn-warning btn-sm" type="button">出</button>{% else %}　{% endif %}
                                <br>
                            {% endfor %}
                        </td>
                    </tr>
                {% endfor %}
            </table>
         </div>

    </div>


    <script>

        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i <cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
  
        var csrftoken = getCookie('csrftoken');
  
        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }
  
        $.ajaxSetup({
            beforeSend: function (xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });
  

        
        // 注文CSV取込
        document.getElementById("btn_upload").addEventListener("click",function(){
            var csv_form=new FormData(document.getElementById("csv_form"));
            var csv1=document.getElementById("csv1");
            if (csv1.value == ""){
                window.alert("注文ファイルを指定してください！");
                return
            };
            $.ajax({
                    'url': '{% url "app1:chumon_imp" %}',
                    'type': 'POST',
                    'data': csv_form,
                    'processData': false,
                    'contentType': false,
                    'cache': false
                })
                .done(function(response){
                    window.location.href = '{% url "app1:index" %}';
                    window.alert("注文を取り込みました！");
                })
        });
        
        

    </script>


</body>
</html>

pi_pro/app1/templates/app1/login.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css">
    <link rel="icon" href="{% static 'tamori.gif' %}">
    <title>Pi-pro（ログイン）</title>
</head>
<body>
    <div class="login flex">
        <form class="form-signin" method="POST">{% csrf_token %}
            <div>
                <div style="margin-top: 10px; text-align: center;"><img src="{% static 'logo.png' %}"></div>
            </div>
            <div>
                <div class="login_title" style="margin-top: 25px;"><img src="{% static 'airliner_6an.gif' %}" style="margin-left: 45px;">　Pi-pro</div>
            </div>
            <div style="margin-top: 20px;">
                <table style="margin-left: auto; margin-right: auto;">
                    <tr>
                        {% if form.errors %}
                            <p style="color: red;">ユーザー名かパスワードが間違っています。</p>
                        {% endif %}
                    </tr>
                    <tr>
                        <td>ログインID：</td>
                        <td><input class="form-control" type="text" name="username" style="width: 150px;"></td>
                    </tr>
                    <tr>
                        <td style="padding-top: 10px; text-align: right;">パスワード：</td>
                        <td style="padding-top: 10px;"><input class="form-control" type="password" name="password" style="width: 150px;"></td>
                    </tr>
                    <tr>
                        <td colspan="2" style="text-align: center; padding-top: 10px;">
                            <button type="submit" class="btn btn-secondary mb-2" style="width: 100%;">ログイン</button>
                        </td>
                    </tr>
                </table>
            </div>
        </form>
    </div>

</body>
</html>

pi_pro/app1/templates/app1/master_img_index.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <title>Pi_pro　マスタ/イメージ図取込</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

</head>
<body>
    <div class="container mt-3 mb-5">
        <!-- メニュー -->
        <div>
            <a href="{% url 'app1:index' %}"><button class="btn btn-outline-primary" type="submit" name="btn_upload">注文一覧に戻る</button></a>
        </div>

        <!-- マスタ取込 -->
        <div class="mt-5 mb-5">
            <h3 class="master_title">マスタ取込</h3>
            <div style="margin-top: 20px;">
                <form>{% csrf_token %}
                    <div class="flex2">
                        <div>マスタ対象：</div>
                        <div>
                            <select class="form-control form-select" name="master_name">
                                {% for i in master_all %}
                                <option value="{{i.name}}">{{i.name}}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <div style="margin-top: 20px;"><input class="form-control" type="file" name="csv1" style="width: 400px;"></div>
                    <div class="flex2" style="margin-top: 20px;">
                        <div>
                            <button class="btn btn-primary" type="submit" formaction="{% url 'app1:master_csv' %}" formmethod="post" formenctype="multipart/form-data">取込</button>
                        </div>
                        <div style="margin-left: 30px;">
                            <button class="btn btn-success" type="submit" formaction="{% url 'app1:download_master' %}" formmethod="post">マスタ出力</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <!-- 画像取り込み -->
        <div style="margin-top: 100px;">
            <h3 class="master_title">イメージ図取込</h3>
            <div style="margin-top: 20px;">
                <form action="{% url 'app1:img_imp' %}" method="POST" enctype="multipart/form-data">{% csrf_token %}
                    <div class="flex2">
                        <div>タイトル：</div>
                        <div style="width: 415px;">{{image_form.title}}</div>
                    </div>
                    <div class="flex2" style="margin-top: 20px;">
                        <div>イメージ図：</div>
                        <div style="width: 400px;">{{image_form.image}}</div>
                    </div>
                    <div style="margin-top: 20px;"><button class="btn btn-primary" type="submit">保存</button></div>
                </form>
            </div>
            <div  class="img-container" style="margin-top: 50px;">
                {% for i in image_all %}
                    <div class="img-item">
                        <div style="height: 200px;"><img src="{{i.image.url}}" style="width: 100%;"></div>
                        <div>{{i.title}}</div>
                        <div><button class="btn btn-secondary btn-sm" id="{{i.image.url}}" name="url_btn">URLをコピー</button></div>
                    </div>
                {% endfor %}
            </div>
        </div>

    </div>

    <script>

        // URLボタン
        var item=document.getElementsByName("url_btn");
        for (var i=0; i<item.length; i++){
            item[i].addEventListener("click",function(){
                navigator.clipboard.writeText("https://pipro.pythonanywhere.com" + this.id);
                window.alert("URLをコピーしました！");
            },false)
        };


    </script>

</body>
</html>